version: '3.7'
services:
  postgres-webhook: 
    build:
      context: ./
      dockerfile: Dockerfile
    network_mode: host
    environment:
      DBNAME: ${DBNAME}
      PGUSER: ${PGUSER}
      PGPASS: ${PGPASS}
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
      WEBHOOKURL: ${WEBHOOKURL}
      TIMEZONE: ${TIMEZONE}
    restart: always
    container_name: postgres-webhook
